<a href="https://colab.research.google.com/github/samikshak02/Python-Basic-Projects./blob/master/Dataset%26pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd
from google.colab import files
uploaded= files.upload()

Saving Chicago_census.csv to Chicago_census (2).csv

In [15]:
filepath="/content/Chicago_census.csv"
df=pd.read_csv(filepath)

In [16]:
df.head()

,Unnamed: 0,ward,pop_2000,pop_2010,change,address,zip
0,0,NaN,52951,56149,6%,2765 WEST SAINT MARY STREET,60647
1,1,2.0,54361,55805,3%,WM WASTE MANAGEMENT 1500,60622
2,2,3.0,40385,53039,31%,17 EAST 38TH STREET,60653
3,3,4.0,51953,54589,5%,31ST ST HARBOR BUILDING LAKEFRONT TRAIL,60653
4,4,5.0,55302,51455,-7%,JACKSON PARK LAGOON SOUTH CORNELL DRIVE,60637

In [17]:
df.tail()

,Unnamed: 0,ward,pop_2000,pop_2010,change,address,zip
45,45,46.0,56587,53784,-5%,UPTOWN BROADWAY BUILDING 4743-4763,60640
46,46,47.0,52108,55074,6%,2153 WEST BERTEAU AVENUE,60618
47,47,48.0,56246,55014,-2%,1025 WEST HOLLYWOOD AVENUE,60660
48,48,49.0,59435,54633,-8%,1426 WEST ESTES AVENUE,60645
49,49,50.0,62383,55809,-11%,2638 WEST NORTH SHORE AVENUE,60645

In [18]:
df.shape

(50, 7)

In [19]:
df.columns

Index(['Unnamed: 0', 'ward', 'pop_2000', 'pop_2010', 'change', 'address',
       'zip'],
      dtype='object')

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  50 non-null     int64
 1   ward        49 non-null     float64
 2   pop_2000    50 non-null     int64
 3   pop_2010    50 non-null     int64
 4   change      50 non-null     object
 5   address     50 non-null     object
 6   zip         50 non-null     int64
dtypes: float64(1), int64(4), object(2)
memory usage: 2.9+ KB

In [22]:
df.describe()

       Unnamed: 0      ward      pop_2000     pop_2010           zip
count    50.00000  49.00000     50.000000     50.00000     50.000000
mean     24.50000  26.00000  57920.320000  53868.82000  60340.420000
std      14.57738  14.28869   6792.731227   1706.45284   2015.139658
min       0.00000   2.00000  40385.000000  51455.00000  46394.000000
25%      12.25000  14.00000  54119.500000  52024.25000  60622.000000
50%      24.50000  26.00000  56600.000000  53907.50000  60635.000000
75%      36.75000  38.00000  62274.500000  55309.50000  60646.750000
max      49.00000  50.00000  80143.000000  56170.00000  60827.000000

In [23]:
df.dtypes

Unnamed: 0      int64
ward          float64
pop_2000        int64
pop_2010        int64
change         object
address        object
zip             int64
dtype: object

In [24]:
df.isnull().sum()

Unnamed: 0    0
ward          1
pop_2000      0
pop_2010      0
change        0
address       0
zip           0
dtype: int64

In [25]:
df.nunique()

Unnamed: 0    50
ward          49
pop_2000      50
pop_2010      50
change        28
address       50
zip           37
dtype: int64

In [26]:
df.sample(5)

,Unnamed: 0,ward,pop_2000,pop_2010,change,address,zip
28,28,29.0,61949,55267,-11%,1241 NORTH RIDGELAND AVENUE,60302
17,17,18.0,55043,52992,-4%,3286 WEST COLUMBUS AVENUE,60652
38,38,39.0,64291,55882,-13%,QUEEN OF ALL SAINTS BASILICA 6280,60646
37,37,38.0,66011,56001,-15%,7307-7331 WEST IRVING PARK ROAD,60706
7,7,8.0,54039,51687,-4%,1346-1352 EAST 75TH STREET,60649

In [30]:
df['zip'].value_counts()

zip
60632    4
60618    3
60645    3
60636    3
60653    2
60641    2
60651    2
60622    2
60647    1
60637    1
46394    1
60628    1
60617    1
60652    1
60805    1
60620    1
60621    1
60629    1
60607    1
60638    1
60649    1
60624    1
60608    1
60623    1
60302    1
60827    1
60634    1
60706    1
60625    1
60646    1
60068    1
60654    1
60614    1
60657    1
60630    1
60640    1
60660    1
Name: count, dtype: int64