<a href="https://colab.research.google.com/github/samikshak02/Python-Basic-Projects./blob/master/SpecialTask.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [6]:
from google.colab import files
uploaded= files.upload()

Saving manifest.csv to manifest (2).csv

In [7]:
filepath="/content/manifest.csv"
df=pd.read_csv(filepath)
df.head()

,date,daily_dataset_slug,daily_dataset_url,episode_count,total_bytes,top_avg_score,median_avg_score
0,2026-06-16,pokemon-tcg-ai-battle-episodes-2026-06-16,https://www.kaggle.com/datasets/kaggle/pokemon...,1277,2854565943,1024.643707,627.771126
1,2026-06-17,pokemon-tcg-ai-battle-episodes-2026-06-17,https://www.kaggle.com/datasets/kaggle/pokemon...,7819,21474554811,1259.804498,761.005766
2,2026-06-18,pokemon-tcg-ai-battle-episodes-2026-06-18,https://www.kaggle.com/datasets/kaggle/pokemon...,6532,21474554331,1327.123541,926.601386
3,2026-06-19,pokemon-tcg-ai-battle-episodes-2026-06-19,https://www.kaggle.com/datasets/kaggle/pokemon...,5426,21472784639,1324.930326,1013.694841
4,2026-06-20,pokemon-tcg-ai-battle-episodes-2026-06-20,https://www.kaggle.com/datasets/kaggle/pokemon...,5178,21474153388,1311.233883,1063.760850

In [8]:
df.tail()

,date,daily_dataset_slug,daily_dataset_url,episode_count,total_bytes,top_avg_score,median_avg_score
15,2026-07-01,pokemon-tcg-ai-battle-episodes-2026-07-01,https://www.kaggle.com/datasets/kaggle/pokemon...,5266,21472709170,1344.584468,1180.260904
16,2026-07-02,pokemon-tcg-ai-battle-episodes-2026-07-02,https://www.kaggle.com/datasets/kaggle/pokemon...,5153,21473785185,1274.779486,1135.927808
17,2026-07-03,pokemon-tcg-ai-battle-episodes-2026-07-03,https://www.kaggle.com/datasets/kaggle/pokemon...,5133,21473781654,1250.921561,1104.464801
18,2026-07-04,pokemon-tcg-ai-battle-episodes-2026-07-04,https://www.kaggle.com/datasets/kaggle/pokemon...,4975,21473046866,1258.026805,1101.422470
19,2026-07-05,pokemon-tcg-ai-battle-episodes-2026-07-05,https://www.kaggle.com/datasets/kaggle/pokemon...,5034,21473460761,1237.003858,1077.617445

In [6]:
df.shape

(20, 7)

In [9]:
df.columns

Index(['date', 'daily_dataset_slug', 'daily_dataset_url', 'episode_count',
       'total_bytes', 'top_avg_score', 'median_avg_score'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                20 non-null     object
 1   daily_dataset_slug  20 non-null     object
 2   daily_dataset_url   20 non-null     object
 3   episode_count       20 non-null     int64
 4   total_bytes         20 non-null     int64
 5   top_avg_score       20 non-null     float64
 6   median_avg_score    20 non-null     float64
dtypes: float64(2), int64(2), object(3)
memory usage: 1.2+ KB

In [11]:
df.describe()

       episode_count   total_bytes  top_avg_score  median_avg_score
count      20.000000  2.000000e+01      20.000000         20.000000
mean     5429.350000  2.054203e+10    1314.028501       1004.259774
std      1193.409678  4.163198e+09      85.725533        141.821615
min      1277.000000  2.854566e+09    1024.643707        627.771126
25%      5115.250000  2.147198e+10    1271.035739       1005.431741
50%      5460.500000  2.147315e+10    1329.560805       1026.606392
75%      5937.250000  2.147394e+10    1368.085382       1102.183053
max      7819.000000  2.147476e+10    1411.126738       1180.260904

In [12]:
df.dtypes

date                   object
daily_dataset_slug     object
daily_dataset_url      object
episode_count           int64
total_bytes             int64
top_avg_score         float64
median_avg_score      float64
dtype: object

In [13]:
df.isnull().sum()

date                  0
daily_dataset_slug    0
daily_dataset_url     0
episode_count         0
total_bytes           0
top_avg_score         0
median_avg_score      0
dtype: int64

In [14]:
df.nunique()

date                  20
daily_dataset_slug    20
daily_dataset_url     20
episode_count         20
total_bytes           20
top_avg_score         20
median_avg_score      20
dtype: int64

In [15]:
df.sample()

,date,daily_dataset_slug,daily_dataset_url,episode_count,total_bytes,top_avg_score,median_avg_score
6,2026-06-22,pokemon-tcg-ai-battle-episodes-2026-06-22,https://www.kaggle.com/datasets/kaggle/pokemon...,5062,21472042818,1346.785101,1049.009917

In [16]:
df.sample(3)

,date,daily_dataset_slug,daily_dataset_url,episode_count,total_bytes,top_avg_score,median_avg_score
16,2026-07-02,pokemon-tcg-ai-battle-episodes-2026-07-02,https://www.kaggle.com/datasets/kaggle/pokemon...,5153,21473785185,1274.779486,1135.927808
17,2026-07-03,pokemon-tcg-ai-battle-episodes-2026-07-03,https://www.kaggle.com/datasets/kaggle/pokemon...,5133,21473781654,1250.921561,1104.464801
18,2026-07-04,pokemon-tcg-ai-battle-episodes-2026-07-04,https://www.kaggle.com/datasets/kaggle/pokemon...,4975,21473046866,1258.026805,1101.422470

In [21]:
df['daily_dataset_url'].value_counts()

daily_dataset_url
https://www.kaggle.com/datasets/kaggle/pokemon-tcg-ai-battle-episodes-2026-06-16    1
https://www.kaggle.com/datasets/kaggle/pokemon-tcg-ai-battle-episodes-2026-06-17    1
https://www.kaggle.com/datasets/kaggle/pokemon-tcg-ai-battle-episodes-2026-06-18    1
https://www.kaggle.com/datasets/kaggle/pokemon-tcg-ai-battle-episodes-2026-06-19    1
https://www.kaggle.com/datasets/kaggle/pokemon-tcg-ai-battle-episodes-2026-06-20    1
https://www.kaggle.com/datasets/kaggle/pokemon-tcg-ai-battle-episodes-2026-06-21    1
https://www.kaggle.com/datasets/kaggle/pokemon-tcg-ai-battle-episodes-2026-06-22    1
https://www.kaggle.com/datasets/kaggle/pokemon-tcg-ai-battle-episodes-2026-06-23    1
https://www.kaggle.com/datasets/kaggle/pokemon-tcg-ai-battle-episodes-2026-06-24    1
https://www.kaggle.com/datasets/kaggle/pokemon-tcg-ai-battle-episodes-2026-06-25    1
https://www.kaggle.com/datasets/kaggle/pokemon-tcg-ai-battle-episodes-2026-06-26    1
https://www.kaggle.com/datasets/kaggle/pokemon-tcg-ai-battle-episodes-2026-06-27    1
https://www.kaggle.com/datasets/kaggle/pokemon-tcg-ai-battle-episodes-2026-06-28    1
https://www.kaggle.com/datasets/kaggle/pokemon-tcg-ai-battle-episodes-2026-06-29    1
https://www.kaggle.com/datasets/kaggle/pokemon-tcg-ai-battle-episodes-2026-06-30    1
https://www.kaggle.com/datasets/kaggle/pokemon-tcg-ai-battle-episodes-2026-07-01    1
https://www.kaggle.com/datasets/kaggle/pokemon-tcg-ai-battle-episodes-2026-07-02    1
https://www.kaggle.com/datasets/kaggle/pokemon-tcg-ai-battle-episodes-2026-07-03    1
https://www.kaggle.com/datasets/kaggle/pokemon-tcg-ai-battle-episodes-2026-07-04    1
https://www.kaggle.com/datasets/kaggle/pokemon-tcg-ai-battle-episodes-2026-07-05    1
Name: count, dtype: int64